# Generated by Django 6.0.1 on 2026-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_remove_productosacademicos_nombrerecurso'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cursosrealizados',
            name='uq_curso_perfil_nombre_fechas',
        ),
        migrations.RemoveConstraint(
            model_name='experiencialaboral',
            name='uq_exp_perfil_empresa_cargo_fechas',
        ),
        migrations.RemoveConstraint(
            model_name='productosacademicos',
            name='uq_prodacad_perfil_nombre_clasif',
        ),
        migrations.RemoveConstraint(
            model_name='productoslaborales',
            name='uq_prodlab_perfil_nombre_fecha',
        ),
        migrations.RemoveConstraint(
            model_name='reconocimientos',
            name='uq_recon_perfil_tipo_fecha_entidad',
        ),
        migrations.RemoveConstraint(
            model_name='ventagarage',
            name='uq_venta_perfil_producto_fecha',
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='lugarempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='productosacademicos',
            name='rutaimagen',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='rutaimagen',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
        ),
    ]
